//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCI.VSP.Web.CrmIFrames.VendorMonitoring {
    
    
    public partial class Actuals {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new PCI.VSP.Web.CrmIFrames.VendorMonitoring.VMMaster Master {
            get {
                return ((PCI.VSP.Web.CrmIFrames.VendorMonitoring.VMMaster)(base.Master));
            }
        }
    }
}
